language: go

stages:
  - diff
  - test

go:
  - 1.12.x
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip
  include:
    - stage: diff
      go: 1.12.x
      script: diff -u <(echo -n) <(gofmt -d -s .)

before_install: go get -u github.com/kyoh86/richgo

script:
  - go get github.com/hashicorp/vault/shamir
  - go get github.com/spf13/cobra
  - go get github.com/xkortex/vprint
  - go get golang.org/x/crypto/ssh/terminal
  - echo $PATH
  - go build -o /tmp/passcrux
  - /tmp/passcrux -h
  - go test -race -v $(go list ./... )
  - echo "travis" | /tmp/passcrux split --ratio 3/5 --stdin | tail -3 | /tmp/passcrux combine --stdin
  - echo "travis" | /tmp/passcrux split --ratio 3/5 -e abc --stdin | tail -3 | /tmp/passcrux combine -e abc --stdin
  - ./tests/end2end.sh

